### ISSUE TITLE
Create CSA PDF output style

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/csand-style#3]
Currently we use Google's puppeteer for PDF output, but the CSA really wants to have an output that exactly looks like this template:

https://downloads.cloudsecurityalliance.org/assets/research/security-guidance/security-guidance-v4-FINAL.pdf

I'm not sure if this is doable via HTML; we might need an alternative solution before we come back to this.

**Comment by opoudjis** [comment]
By way of explanation: Google's Puppeteer is a Node library that accesses Headless Chrome, so it can be used to print HTML to PDF via Chrome. It respects your `media @print` CSS style. The question here is whether a browser-rendered HTML can generate something like the link.

Page numbers in the footer, and indeed a footer, which make me doubtful that a Browser can do it; @pierrefortier? At least there is no paginated table of contents, which really would be a deal-breaker. The sidebar on the other hand looks like classic Browser HTML, and would be quite hard for Word to do. 

@ronaldtse, have the CSA told you how they generate it? If they are generating those sidebars via Word instead of HTML, I'm kind of impressed that they'd go to the bother.

**Comment by ronaldtse** [comment]
@opoudjis the entire PDF is manually created. But perhaps their designer uses whatever tool Adobe has (InDesign)?

**Comment by opoudjis** [comment]
CSA need to communicate how much variation they expect in that sidebar. If the sidebar is to be manually crafted for each different standard, there is not much point in automating its formatting. At best, the standard source needs to provide the icon corresponding to each header in the sidebar.

**Comment by ronaldtse** [comment]
I think they just want it to be pretty. Every document is done manually and differently. Perhaps the easiest way is to allow usage of the Asciidoctor icons? (i.e. they set it for each section prior to generation of the ToC)

**Comment by opoudjis** [comment]
Yes, if they preset the icons, something can be done. Of course, we also need to stretch the icons to fit the entire length of the page, but I'm hoping that instead they can just be evenly spaced, against a background of the same colour.

Btw, the sidebar means HTML, not Word. I'll see if we can still put page numbers in a footer, but I'm pretty sure we can't. (So they'll have to pick one of the two: fancy sidebar, or footer page numbers.)

**Comment by opoudjis** [comment]
... Further investigation: it looks like Puppeteer does support page numbers, but very inflexibly, and using Chrome-specific HTML. If you even want to leave out the page number from the title page, you end up having to generate two pdfs, one for the title page and one for the paginated material, and then concatenate the PDFs. And you can forget custom page numbering such as roman numerals.

https://github.com/GoogleChrome/puppeteer/issues/373
https://github.com/GoogleChrome/puppeteer/pull/1625

This is a partial solution, not a complete one.

**Comment by ronaldtse** [comment]
Hmm... Again makes me think that direct PDF is a better solution https://github.com/gettalong/hexapdf

**Comment by opoudjis** [comment]
Ugh. Please no.

**Comment by ronaldtse** [comment]
PDF will be a future thing.
